name: Build
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Starting workflow for ${{ matrix.os }}
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn install
      - name: bundle javascript
        run: yarn tsc
      - name: build
        run: yarn run make
      - run: ls
      - run: ls out
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: out/**/*.zip