name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn
    - name: Bundle/Compile Javascript
      run: yarn build
    - name: Build
      run: yarn make

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn
    - name: Bundle/Compile Javascript
      run: yarn build
    - name: Build
      run: yarn make
    - run: ls

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn
    - name: Bundle/Compile Javascript
      run: yarn build
    - name: Build
      run: yarn make
    - run: ls