name: Build
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Starting workflow for ${{ matrix.os }}
        run: echo ${{ matrix.os }}
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn install
      - name: bundle javascript
        run: yarn tsc
      - name: build
        run: yarn make
      - run: ls
      - run: ls out
      - run: tree out
      - run: ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: out/**/*.zip